logging.level.uk.gov.nationalarchives.discovery.taxonomy: DEBUG

spring.activemq:
 broker-url: "tcp://localhost:61616"
 user: "system"
 password: "manager"
 categorise-doc-queue-name: CATEGORISE.DOCUMENTS
 publish-categories-queue-name: PUBLISH.CATEGORIES

mongo.categories:
 hosts: localhost
 ports: 27017
 database: taxonomy

solr.cloud:
 read:
  host: http://localhost:12602/solr/DISCOVERY/
  query-page-size: 1000
 write:
  host: http://localhost:12602/solr/DISCOVERY/
  commit-within: 10000



scheduler.update-solr:
 bulk-update-size: 5000
 rate-between-updates: 2000