spring.activemq:
 broker-url: "tcp://localhost:61616"
 user: "system"
 password: "manager"
 categorise-doc-queue-name: CATEGORISE.DOCUMENTS
 publish-categories-queue-name: PUBLISH.CATEGORIES

mongo.categories:
 hosts: localhost
 ports: 27017
 database: taxonomy

solr.cloud:
# read.host: http://wb-solrapp2:8985/solr/IAVIEWS_SNAPSHOT/
 read.host: http://localhost:12602/solr/DISCOVERY/
 write:
  host: http://localhost:8983/solr/IAView_subset/
  commit-within: 10000



scheduler.update-solr:
 bulk-update-size: 2000
 rate-between-updates: 2000